# =============================================================================
# CreateAppImage.cmake
# =============================================================================
#
# Downloads appimagetool and generates the final AppImage file from the
# prepared AppDir structure.
#
# This module:
# 1. Downloads appimagetool if not present
# 2. Creates a custom target 'appimage' for AppImage generation
# 3. Handles environments without FUSE using APPIMAGE_EXTRACT_AND_RUN=1
#
# =============================================================================

if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    return()
endif()

# Ensure APPDIR variables are set
if(NOT DEFINED FLYSIGHT_APPDIR_PATH)
    set(FLYSIGHT_APPDIR_PATH "${CMAKE_INSTALL_PREFIX}/FlySightViewer.AppDir")
    set(FLYSIGHT_APPDIR_USR "${FLYSIGHT_APPDIR_PATH}/usr")
endif()

# =============================================================================
# Configuration
# =============================================================================

# appimagetool download configuration
# Detect architecture for correct download
if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64|ARM64")
    set(APPIMAGETOOL_ARCH "aarch64")
else()
    set(APPIMAGETOOL_ARCH "x86_64")
endif()

set(APPIMAGETOOL_VERSION "continuous" CACHE STRING "appimagetool version to download")
set(APPIMAGETOOL_URL "https://github.com/AppImage/appimagetool/releases/download/${APPIMAGETOOL_VERSION}/appimagetool-${APPIMAGETOOL_ARCH}.AppImage")
set(APPIMAGETOOL_DOWNLOAD_DIR "${CMAKE_BINARY_DIR}/tools")
set(APPIMAGETOOL_PATH "${APPIMAGETOOL_DOWNLOAD_DIR}/appimagetool")

# Output AppImage configuration
set(APPIMAGE_OUTPUT_DIR "${CMAKE_BINARY_DIR}" CACHE PATH "Directory for generated AppImage")
set(APPIMAGE_FILENAME "FlySightViewer-${PROJECT_VERSION}-${APPIMAGETOOL_ARCH}.AppImage" CACHE STRING "Output AppImage filename")

# =============================================================================
# Download appimagetool at configure time
# =============================================================================

message(STATUS "CreateAppImage: Configuring AppImage generation")
message(STATUS "  Architecture: ${APPIMAGETOOL_ARCH}")
message(STATUS "  Output: ${APPIMAGE_OUTPUT_DIR}/${APPIMAGE_FILENAME}")

# Create tools directory
file(MAKE_DIRECTORY "${APPIMAGETOOL_DOWNLOAD_DIR}")

# Download appimagetool if not present
if(NOT EXISTS "${APPIMAGETOOL_PATH}")
    message(STATUS "Downloading appimagetool...")
    file(DOWNLOAD
        "${APPIMAGETOOL_URL}"
        "${APPIMAGETOOL_PATH}"
        SHOW_PROGRESS
        STATUS download_status
        TLS_VERIFY ON
    )
    list(GET download_status 0 download_error)
    if(download_error)
        list(GET download_status 1 download_message)
        message(WARNING "Failed to download appimagetool: ${download_message}")
        message(WARNING "AppImage generation will not be available")
        set(FLYSIGHT_APPIMAGETOOL_AVAILABLE FALSE CACHE INTERNAL "")
    else()
        # Make it executable
        execute_process(COMMAND chmod +x "${APPIMAGETOOL_PATH}")
        message(STATUS "appimagetool downloaded successfully")
        set(FLYSIGHT_APPIMAGETOOL_AVAILABLE TRUE CACHE INTERNAL "")
    endif()
else()
    message(STATUS "Using cached appimagetool: ${APPIMAGETOOL_PATH}")
    set(FLYSIGHT_APPIMAGETOOL_AVAILABLE TRUE CACHE INTERNAL "")
endif()

# =============================================================================
# Custom target for AppImage generation
# =============================================================================

if(FLYSIGHT_APPIMAGETOOL_AVAILABLE)
    # Create a script that will be run by the custom target
    set(APPIMAGE_SCRIPT "${CMAKE_BINARY_DIR}/create_appimage.sh")

    file(WRITE "${APPIMAGE_SCRIPT}" [=[#!/bin/bash
# AppImage creation script for FlySight Viewer
# Generated by CMake - do not edit directly

set -e

APPDIR="@FLYSIGHT_APPDIR_PATH@"
APPIMAGETOOL="@APPIMAGETOOL_PATH@"
OUTPUT_DIR="@APPIMAGE_OUTPUT_DIR@"
OUTPUT_NAME="@APPIMAGE_FILENAME@"
OUTPUT_PATH="${OUTPUT_DIR}/${OUTPUT_NAME}"

echo "=== Creating AppImage ==="
echo "AppDir: ${APPDIR}"
echo "Output: ${OUTPUT_PATH}"

# Verify AppDir exists
if [ ! -d "${APPDIR}" ]; then
    echo "ERROR: AppDir not found at ${APPDIR}"
    echo "Run 'cmake --install <build-dir>' first to create the AppDir"
    exit 1
fi

# Verify AppRun exists and is executable
if [ ! -x "${APPDIR}/AppRun" ]; then
    echo "ERROR: AppRun not found or not executable"
    exit 1
fi

# Verify desktop file exists
if [ ! -f "${APPDIR}/FlySightViewer.desktop" ]; then
    echo "ERROR: Desktop file not found"
    exit 1
fi

# Verify executable exists
if [ ! -x "${APPDIR}/usr/bin/FlySightViewer" ]; then
    echo "ERROR: FlySightViewer executable not found"
    exit 1
fi

# Create output directory if needed
mkdir -p "${OUTPUT_DIR}"

# Set environment for AppImage extraction (works without FUSE)
export APPIMAGE_EXTRACT_AND_RUN=1

# Remove old AppImage if it exists
rm -f "${OUTPUT_PATH}"

# Run appimagetool
echo "Running appimagetool..."
"${APPIMAGETOOL}" "${APPDIR}" "${OUTPUT_PATH}"

# Verify output
if [ -f "${OUTPUT_PATH}" ]; then
    echo "=== AppImage created successfully ==="
    echo "Output: ${OUTPUT_PATH}"
    ls -lh "${OUTPUT_PATH}"

    # Make it executable
    chmod +x "${OUTPUT_PATH}"

    echo ""
    echo "To run the AppImage:"
    echo "  ${OUTPUT_PATH}"
    echo ""
    echo "Or extract and run (if FUSE is unavailable):"
    echo "  ${OUTPUT_PATH} --appimage-extract-and-run"
else
    echo "ERROR: AppImage was not created"
    exit 1
fi
]=])

    # Configure the script with actual paths
    string(CONFIGURE "${APPIMAGE_SCRIPT}" APPIMAGE_SCRIPT_CONTENT @ONLY)
    file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/create_appimage.sh"
         CONTENT "${APPIMAGE_SCRIPT_CONTENT}")

    # Make script executable at configure time
    # Note: file(GENERATE) runs at generation time, so we use install(CODE) for chmod
    install(CODE "
        execute_process(COMMAND chmod +x \"${CMAKE_BINARY_DIR}/create_appimage.sh\")
    " COMPONENT AppImage)

    # Add custom target for AppImage creation
    add_custom_target(appimage
        COMMAND "${CMAKE_COMMAND}" --install "${CMAKE_BINARY_DIR}" --config $<CONFIG>
        COMMAND bash "${CMAKE_BINARY_DIR}/create_appimage.sh"
        WORKING_DIRECTORY "${CMAKE_BINARY_DIR}"
        COMMENT "Creating AppImage..."
        VERBATIM
    )

    # Make the appimage target depend on the main target
    add_dependencies(appimage FlySightViewer flysight_cpp_bridge)

    message(STATUS "CreateAppImage: 'appimage' target available")
    message(STATUS "  Build with: cmake --build <build-dir> --target appimage")
else()
    message(STATUS "CreateAppImage: appimagetool not available")
    message(STATUS "  AppImage generation disabled")
endif()

# =============================================================================
# Alternative: Install-time AppImage creation
# =============================================================================

# This provides an alternative way to create AppImage during install
# Useful for CI/CD pipelines that run 'cmake --install' directly

option(FLYSIGHT_CREATE_APPIMAGE_ON_INSTALL "Create AppImage during cmake --install" OFF)

if(FLYSIGHT_CREATE_APPIMAGE_ON_INSTALL AND FLYSIGHT_APPIMAGETOOL_AVAILABLE)
    install(CODE "
        message(STATUS \"Creating AppImage...\")

        set(APPDIR \"${FLYSIGHT_APPDIR_PATH}\")
        set(APPIMAGETOOL \"${APPIMAGETOOL_PATH}\")
        set(OUTPUT_DIR \"${APPIMAGE_OUTPUT_DIR}\")
        set(OUTPUT_NAME \"${APPIMAGE_FILENAME}\")
        set(OUTPUT_PATH \"\${OUTPUT_DIR}/\${OUTPUT_NAME}\")

        # Set environment for FUSE-less operation
        set(ENV{APPIMAGE_EXTRACT_AND_RUN} \"1\")

        # Run appimagetool
        execute_process(
            COMMAND \"\${APPIMAGETOOL}\" \"\${APPDIR}\" \"\${OUTPUT_PATH}\"
            RESULT_VARIABLE appimage_result
            OUTPUT_VARIABLE appimage_output
            ERROR_VARIABLE appimage_error
        )

        if(appimage_result EQUAL 0)
            message(STATUS \"AppImage created: \${OUTPUT_PATH}\")
            # Make it executable
            execute_process(COMMAND chmod +x \"\${OUTPUT_PATH}\")
        else()
            message(WARNING \"Failed to create AppImage:\")
            message(STATUS \"  \${appimage_error}\")
        endif()
    " COMPONENT AppImage)
endif()

message(STATUS "CreateAppImage.cmake: Configuration complete")
